### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by djratza** [midorineko/rpi_automation#4]
Hello, I would like to add more codes, there are online generators, problem is I don't understand for example for on 124242435242434242424242424242524243424242, how is this transformed from HEX, or binary? Could you please help?

**Comment by midorineko** [comment]
hey there buddy, sorry I don't use git hub or this repository very much anymore, but I would like to help you. What module are you working on?

**Comment by djratza** [comment]
Hi,

I am using the Livolo switch.

**Comment by djratza** [comment]
And I need more codes to control the switch, as you have one remote and the 11 buttons in your script

**Comment by djratza** [comment]
I need more on codes :D, if you could help
